stages:
  - setup

variables:
  # Ort der virtuellen Umgebung
  VENV_PATH: "/data/gitlab/builds/runner/.venv"

default:
  before_script:
   - export CUDA_ROOT=/usr/local/cuda
   - export CFLAGS="-I/usr/local/cuda/include"
   - export CXXFLAGS="-I/usr/local/cuda/include"
   - export C_INCLUDE_PATH=/usr/local/cuda/include
   - export CPLUS_INCLUDE_PATH=/usr/local/cuda/include
   - export LIBRARY_PATH=/usr/local/cuda/lib64
   - export PYTHONPATH=/usr/lib/python3.10/dist-packages:${CI_PROJECT_DIR}:$PYTHONPATH  
   - export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu:$LD_LIBRARY_PATH
   - export PIP_CACHE_DIR=$CI_PROJECT_DIR/.cache/pip

setup-job:
  stage: setup
  script:
    - mkdir -p $PIP_CACHE_DIR
    - python3 -m venv .venv
    - source .venv/bin/activate
    - ls -l /usr/local/cuda/include/cuda.h
    - pip install --upgrade pip
    - pip install torch==2.6.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu126 -q
    - pip install -r requirements.txt
    - python3 -c "import tensorrt; print(tensorrt.__version__)"
    - dvc pull --allow-missing    # damit nicht nach dvc dateien gesucht wird, die ich noch nicht gepusht habe

  # umgebungsvariablen für unterschiedliche Models
  # hier measure.export für alle skripte starten
    - python3 -m measure.export
    # - python3 -m measure.export_vision
    # - python3 measure/data_to_numpy.py

    - dvc remote modify upload user $DVC_Sciebo_Upload_USER
    - dvc remote modify upload password $DVC_Sciebo_Upload_PASSWORD
    # - dvc exp remove --all      #  damit dvc nicht nach dieser alten datei sucht

    # umgebungsvariablen für unterschiedliche models und quantisierungsmethoden
    - python3 -m measure.mini_measure
    #- MODEL_TYPE=vision python3 -m measure.mini_measure_vision
    #- python3 -m measure.tegrastats_vision

    - python3 -m measure.tegrastats
 
    - python3 -m measure.accuracy_comparison

    - python3 -m plots.plots

    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan github.com >> ~/.ssh/known_hosts

    - git config --global user.email "ci@example.com"
    - git config --global user.name "CI Runner"
    - dvc push -r upload  # 14 files pushed
    - dvc exp push -r upload -f git@github.com:iksnagreb/finn-transformers.git    # zweiter Teil funktioniert noch nicht

  tags:
    - jetson


# weiter mit vision and language
