"""Acquire vision benchmark JSON files from DVC experiments.

Run this file from any working directory, for example:

	python summary_plots/data_for_plots/data_acquisition.py --dry-run
	python summary_plots/data_for_plots/data_acquisition.py

The script applies each experiment, copies the files generated by that
experiment, and restores the checkout before moving to the next one.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_ROOT = REPOSITORY_ROOT / "outputs" / "vision" / "plot"
DATA_ROOT = Path(__file__).resolve().parent

SOURCE_FILES = {
	"latency_throughput.json": "latency_throughput_{power}.json",
	"latency_results_batch.json": "latency_{power}.json",
	"throughput_results.json": "throughput_{power}.json",
}


# Add or remove experiments here. The experiment ID is the key; the remaining
# fields determine the destination path and output filenames.
EXPERIMENTS = {
	"ci-149099-590654": {"model": "base2", "power": "15w", "mode": ("int8", "ort_int8")},
	"ci-149017-590270": {"model": "base2", "power": "30w", "mode": ("int8", "ort_int8")},
	"ci-149075-590584": {"model": "base2", "power": "50w", "mode": ("int8", "ort_int8")},
	"ci-148567-588762": {"model": "base4", "power": "15w", "mode": ("int8", "ort_int8")},
	"ci-149008-590221": {"model": "base4", "power": "30w", "mode": ("int8", "ort_int8")},
	"ci-148580-588796": {"model": "base4", "power": "50w", "mode": ("int8", "ort_int8")},
	"ci-147861-586679": {"model": "base", "power": "15w", "mode": "fp32"},
	"ci-144377-571533": {"model": "base", "power": "30w", "mode": "fp32"},
	"ci-139320-555878": {"model": "base", "power": "50w", "mode": "fp32"},
	"ci-144941-573891": {"model": "base", "power": "15w", "mode": "fp16"},
	"ci-147874-586629": {"model": "base", "power": "30w", "mode": "fp16"},
	"ci-144854-573492": {"model": "base", "power": "50w", "mode": "fp16"},
}


def run(command: list[str], dry_run: bool) -> None:
	"""Run a repository command unless this is a dry run."""
	print(f"$ {' '.join(command)}")
	if not dry_run:
		subprocess.run(command, cwd=REPOSITORY_ROOT, check=True)


def acquire(experiment_id: str, experiment: dict[str, str | tuple[str, ...]], dry_run: bool) -> None:
	model = experiment["model"]
	power = experiment["power"]

	run(["dvc", "exp", "apply", experiment_id], dry_run)
	modes = (experiment["mode"],) if isinstance(experiment["mode"], str) else experiment["mode"]
	for mode in modes:
		destination = DATA_ROOT / model / mode
		print(f"Acquiring {experiment_id} -> {destination.relative_to(REPOSITORY_ROOT)}")

		if not dry_run:
			destination.mkdir(parents=True, exist_ok=True)

		for source_name, destination_template in SOURCE_FILES.items():
			source = OUTPUT_ROOT / mode.upper() / source_name
			destination_name = destination_template.format(power=power)
			target = destination / destination_name
			print(f"  {source.relative_to(REPOSITORY_ROOT)} -> {target.relative_to(REPOSITORY_ROOT)}")
			if not dry_run:
				if not source.is_file():
					raise FileNotFoundError(f"Expected experiment output was not found: {source}")
				shutil.copy2(source, target)


def restore_checkout(dry_run: bool) -> None:
	"""Restore tracked experiment changes and remove generated vision outputs."""
	run(["git", "reset", "--hard", "HEAD"], dry_run)
	run(["git", "clean", "-fd", "--", "outputs/vision"], dry_run)


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument(
		"experiments",
		nargs="*",
		metavar="EXPERIMENT_ID",
		help="Experiment IDs to acquire (default: all IDs in EXPERIMENTS).",
	)
	parser.add_argument(
		"--dry-run",
		action="store_true",
		help="Print DVC, copy, and restore operations without changing files.",
	)
	return parser.parse_args()


def main() -> None:
	args = parse_args()
	experiment_ids = args.experiments or list(EXPERIMENTS)
	unknown_ids = [experiment_id for experiment_id in experiment_ids if experiment_id not in EXPERIMENTS]
	if unknown_ids:
		raise SystemExit(f"Unknown experiment ID(s): {', '.join(unknown_ids)}")

	try:
		for experiment_id in experiment_ids:
			acquire(experiment_id, EXPERIMENTS[experiment_id], args.dry_run)
	finally:
		restore_checkout(args.dry_run)


if __name__ == "__main__":
	main()
